routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HeaderController@index')->name('index');
Route::get('/background','IntroductionController@index')->name('introduction');
Route::get('/our-work','DoingController@index')->name('doing');
Route::get('/our-work-filter/{filter_category_content_id}','DoingController@doingFilter')->name('doing-filter');
Route::get('/our-work/detail/{content_id}','DoingController@detail')->name('doing.detail');
Route::get('/testimonials','CommentController@index')->name('comment');
Route::get('/additional-services','AdditionalServiceController@index')->name('additional-service');
Route::get('/additional-service/detail/{content_id}','AdditionalServiceController@detail')->name('additional-service.detail');
Route::get('/contact','ContactController@index')->name('contact');
Route::post('/contact/send-email','ContactController@sendEmail')->name('contact.send-email');
//['middleware'=>'auth'] , 
Route::name('admin.')->prefix('admin')->group(function () { 
    // Route::get('/','HeaderController@manageHeader')->name('manage-header');
    Route::name('header.')->prefix('header')->group(function () { 
        Route::get('/','HeaderController@manageHeader')->name('manage-header');
        Route::post('/edit','HeaderController@editHeader')->name('edit');
    });

    Route::name('introduction.')->prefix('background')->group(function () { 
        Route::get('/','IntroductionController@manageIntroduction')->name('manage-introduction');
        Route::post('/edit','IntroductionController@editIntroduction')->name('edit');
        Route::post('/validator-files-save','IntroductionController@validatorFilesSave')->name('validator-files-save');
    });

    Route::name('doing.')->prefix('our-work')->group(function () { 
        Route::get('/','DoingController@manageDoing')->name('manage-doing');
        Route::get('/add','DoingController@addDoing')->name('add');
        Route::post('/edit','DoingController@editDoing')->name('edit');
        Route::post('/add-and-edit-save','DoingController@addAndEditSaveDoing')->name('add-and-edit-save');
        Route::get('{content_id}/delete','DoingController@deleteDoing')->name('delete');
        Route::get('{content_id}/edit-content-doing','DoingController@editContentDoing')->name('edit-content-doing');

        Route::get('{id_category_content}/get-content-doing-by-id-category-content','DoingController@getContentDoingByIdCategoryContent')->name('get-content-doing-by-id-category-content');
        Route::post('/set-order','DoingController@setOrder')->name('set-order');

        Route::get('get-content-highlight-doing','DoingController@getContentHighlightDoing')->name('get-content-highlight-doing');
        Route::post('/set-highlight-order','DoingController@setHighlightOrder')->name('set-highlight-order');
    });
    Route::name('comment.')->prefix('testimonials')->group(function () { 
        Route::get('/','CommentController@manageComment')->name('manage-comment');
        Route::post('/edit-comment','CommentController@editComment')->name('edit-comment');

        Route::get('/add-customer-content','CommentController@addContentCustomer')->name('add-content');
        Route::get('{content_id}/edit-customer-content','CommentController@editContentCustomer')->name('edit-customer-content');
        Route::post('/add-and-edit-save-customer-content','CommentController@addAndEditSaveContentCustomer')->name('add-and-edit-save-customer-content');

        Route::get('/add-youtube-content','CommentController@addContentYoutube')->name('add-youtube');
        Route::get('{content_id}/edit-youtube-content','CommentController@editContentYoutube')->name('edit-youtube-content');
        Route::post('/add-and-edit-save-youtube-content','CommentController@addAndEditSaveContentYoutube')->name('add-and-edit-save-youtube-content');

        Route::get('{content_id}/delete','CommentController@deleteContent')->name('delete');


        Route::get('get-content-youtube-comment-order','CommentController@getContentYoutubeCommentOrder')->name('get-content-youtube-comment-order');
        Route::post('/set-youtube-order','CommentController@setYoutubeOrder')->name('set-youtube-order');
        Route::post('/set-comment-order','CommentController@setCommentOrder')->name('set-comment-order');
        
    });

    Route::name('additional-service.')->prefix('additional-services')->group(function () { 
        Route::get('/','AdditionalServiceController@manageAdditionalService')->name('manage-additional-service');
        Route::post('/edit-additional-service','AdditionalServiceController@editAdditionalService')->name('edit-additional-service');
        Route::get('/add-content','AdditionalServiceController@addContent')->name('add-content');
        Route::get('{content_id}/edit-content','AdditionalServiceController@editContent')->name('edit-content');
        Route::post('/add-and-edit-save','AdditionalServiceController@addAndEditSaveContent')->name('add-and-edit-save');
        Route::get('{content_id}/delete','AdditionalServiceController@deleteContent')->name('delete');
    });

    Route::name('contact.')->prefix('contact')->group(function () { 
        Route::get('/','ContactController@manageContact')->name('manage-contact');
        Route::post('/edit','ContactController@editContact')->name('edit');

        Route::get('/add-content-email','ContactController@addContentEmail')->name('add-content-email');
        Route::get('{content_id}/edit-email-content','ContactController@editEmailContent')->name('edit-email-content');
        Route::post('/add-and-edit-email-save','ContactController@addAndEditEmailSaveContent')->name('add-and-edit-email-save');
        Route::get('{content_id}/delete','ContactController@deleteContent')->name('delete');

        Route::get('/add-content-qr','ContactController@addContentQR')->name('add-content-qr');
        Route::get('{content_id}/edit-qr-content','ContactController@editContentQR')->name('edit-qr-content');
        Route::post('/add-and-edit-qr-save','ContactController@addAndEditQRSaveContent')->name('add-and-edit-qr-save');

        Route::get('{content_id}/detail-send-email-content','ContactController@detailSendEmailContent')->name('detail-send-email-content');
    });
    
    Route::name('manage-admin.')->prefix('manage-admin')->group(function () { 
        Route::get('/','ManageAdminController@manageAdmin')->name('manage-admin');
        Route::get('/add-admin','ManageAdminController@addAdmin')->name('add-admin');
        Route::post('/add-and-edit-admin-save','ManageAdminController@addAndEditAdminSave')->name('add-and-edit-admin-save');
        Route::get('{user_id}/delete','ManageAdminController@deleteAdmin')->name('delete-admin');
        Route::get('{user_id}/edit-manage-admin','ManageAdminController@editManageAdmin')->name('edit-manage-admin');
        Route::post('/edit-password-save','ManageAdminController@editPasswordSave')->name('edit-password-save');
    });

    Route::get('/','AdminHomeController@adminHome')->name('admin-home');
    
    Route::name('admin-home.')->prefix('admin-home')->group(function () {
        Route::get('/','AdminHomeController@adminHome')->name('admin-home');
        Route::get('{content_id}/delete','AdminHomeController@deleteContent')->name('delete');
    });
});
Route::get('/home','AdminHomeController@adminHome')->name('admin-home');
Route::name('helper.')->prefix('helper')->group(function () { 
    Route::post('/file-delete','HelperController@fileDelete')->name('file-delete');
    Route::post('/files-save','HelperController@filesSave')->name('files-save');
});
// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes(['register' => false , 'home' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

app/ManuOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image ;
use App\Content;
use App\Font;

class ManuOption extends Model
{
    static $header_id = '1';
    static $introduction_id = '2';
    static $doing_id = '3';
    static $comment_id = '4';
    static $additional_service_id = '5';
    static $contact_id = '6';

    static $default_image_path = '/images/default-image.png' ;

    public function getImagesAttribute()
    {
        $images = Image::where('manu_option_id' , $this->id)->get();

        foreach ($images as $key => $image) {
            $image = defaultImage($image);
        }

        return $images ;
    }

    public function getMainImageAttribute()
    {

        $image = Image::where('manu_option_id' , $this->id)->where('is_main','1')->first();
        
        $image = defaultImage($image);
        return $image ;
    
    }

    public function getNoMainImageAttribute()
    {
        $image = Image::where('manu_option_id' , $this->id)->where('is_main','!=','1')->first();
        // dd($image[0]);
        $image = defaultImage($image);

        return $image ;

    }

    public function getContentsAttribute()
    {
        return Content::where('manu_option_id' , $this->id)->get();
    }

    public function getFontAttribute()
    {
        return Font::where('id' , $this->font_id)->first();
    }

}

resources/views/comment/manage-add-customer-content.blade.php
@extends('layout.main_admin')
@section('style')  

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/css/fileinput.min.css">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')

	<div class="container-fluid">
		{!! Form::open(['route'=>'admin.comment.add-and-edit-save-customer-content', 'method', 'POST', 'class' => 'form' , 'enctype' => "multipart/form-data"]) !!}
			{!! Form::hidden('status','add') !!}
			<h4 class="header-text">เพิ่มความเห็นจากลูกค้า</h4>
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								<label>ชื่อ (TH)</label>
								{!! Form::text('name_th',old('name_th'),['class'=> 'form-control', 'required' ]) !!}
								{!! customValidator('name_th',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>ชื่อ (EN)</label>
								{!! Form::text('name_eng',old('name_eng'),['class'=> 'form-control', 'required' ]) !!}
								{!! customValidator('name_eng',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>ตำแหน่ง (TH)</label>
								{!! Form::text('position_th',old('position_th'),['class'=> 'form-control ', 'required' ]) !!}
									{!! customValidator('position_th',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>ตำแหน่ง (EN)</label>
								{!! Form::text('position_eng',old('position_eng'),['class'=> 'form-control ', 'required' ]) !!}
								{!! customValidator('position_eng',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>ความคิดเห็น (TH)</label>
								{!! Form::textarea('comment_th',old('comment_th'),['class'=> 'form-control summernote', 'required' ]) !!}
								{!! customValidator('comment_th',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>ความคิดเห็น (EN)</label>
								{!! Form::textarea('comment_eng',old('comment_eng'),['class'=> 'form-control summernote', 'required' ]) !!}
								{!! customValidator('comment_eng',$errors) !!}
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-12">
							<div class="form-group">
								<label>รูปภาพ</label>
								<div class="file-loading">
									<input name="files[]" type="file" class="files" multiple>
								</div>
								{!! customValidator('files',$errors) !!}
							</div>
						</div>
					</div>
					<input type="submit" class="btn btn-primary btn-submit mt-3" value="บันทึก">
				</div>
			</div>
		{!! Form::close() !!}
	</div>


	<script >
		//  set data
		var comment = JSON.parse('<?php print_r(json_encode($comment)); ?>');
		now_manu = comment.link ;
	</script>
@endsection
@section('script')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/js/fileinput.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
	
    $('.summernote').summernote({
			height: 200,
			toolbar: [
				['style', ['style']],
				['font', ['bold', 'italic', 'underline', 'clear']],
				['fontname', ['fontname']],
				['fontsize', ['fontsize']],
				['height', ['height']],
				['color', ['color']],
				['para', ['ul', 'ol', 'paragraph']],
				['table', ['table']],
				['insert', ['link', 'picture', 'video']],
				['view', ['codeview', 'help']],
			],
			fontNames: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
			fontNamesIgnoreCheck: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
 			styleTags: [
				'p',
				'h3',
				'h4',
				'h5',
				'h6',{
					tag : 'p',
					title : 'Font Light',
					style : 'Font Light',
					className : 'Font-Light',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Medium',
					style : 'Font Medium',
					className : 'Font-Medium',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Semibold',
					style : 'Font Semibold',
					className : 'Font-Semibold',
					value : 'p'
				}
			],
    });

		$(".files").fileinput({
			maxFileCount: 1,
			validateInitialCount: true,
			language: 'en',
			showCaption: true,
			showPreview: true,
			showRemove: true,
			showUpload: false, // <------ just set this from true to false
			showCancel: true,
			showUploadedThumbs: true,
			autoOrientImage: false,
			browseOnZoneClick: true,
			allowedFileExtensions: ["jpg", "png"]
		});
</script>
@endsection

resources/views/comment/manage-add-youtube-content.blade.php
@extends('layout.main_admin')
@section('style')  

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/css/fileinput.min.css">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')

	<div class="container-fluid">
		{!! Form::open(['route'=>'admin.comment.add-and-edit-save-youtube-content', 'method', 'POST', 'class' => 'form' , 'enctype' => "multipart/form-data"]) !!}
			{!! Form::hidden('status','add') !!}
			<h4 class="header-text">เพิ่มลิงก์ Youtube</h4>
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								<label>ลิงก์ Youtube</label>
								{!! Form::text('path_youtube',old('path_youtube'),['class'=> 'form-control ', 'required' ]) !!}
								{!! customValidator('path_youtube',$errors) !!}
							</div>
						</div>
						<div class="w-100"></div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>คำอธิบาย (TH)</label>
								{!! Form::textarea('detail_youtube_th',old('detail_youtube_th'),['class'=> 'form-control summernote', 'required' ]) !!}
								{!! customValidator('detail_youtube_th',$errors) !!}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label>คำอธิบาย (EN)</label>
								{!! Form::textarea('detail_youtube_eng',old('detail_youtube_eng'),['class'=> 'form-control summernote', 'required' ]) !!}
								{!! customValidator('detail_youtube_eng',$errors) !!}
							</div>
						</div>
					</div>
					<input type="submit" class="btn btn-primary btn-submit mt-3" value="บันทึก">
				</div>
			</div>
		{!! Form::close() !!}
	</div>

	<script >
		//  set data
		var comment = JSON.parse('<?php print_r(json_encode($comment)); ?>');
		now_manu = comment.link ;
	</script>
@endsection
@section('script')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/js/fileinput.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>

    $('.summernote').summernote({
			height: 200,
			toolbar: [
				['style', ['style']],
				['font', ['bold', 'italic', 'underline', 'clear']],
				['fontname', ['fontname']],
				['fontsize', ['fontsize']],
				['height', ['height']],
				['color', ['color']],
				['para', ['ul', 'ol', 'paragraph']],
				['table', ['table']],
				['insert', ['link', 'picture', 'video']],
				['view', ['codeview', 'help']],
			],
			fontNames: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
			fontNamesIgnoreCheck: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
 			styleTags: [
				'p',
				'h3',
				'h4',
				'h5',
				'h6',{
					tag : 'p',
					title : 'Font Light',
					style : 'Font Light',
					className : 'Font-Light',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Medium',
					style : 'Font Medium',
					className : 'Font-Medium',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Semibold',
					style : 'Font Semibold',
					className : 'Font-Semibold',
					value : 'p'
				}
			],
    });

    $("#files").fileinput({
        language: 'en',
        showCaption: true,
        showPreview: true,
        showRemove: true,
        showUpload: false, // <------ just set this from true to false
        showCancel: true,
    		browseOnZoneClick: true,
        showUploadedThumbs: true
     });

</script>
@endsection

resources/views/comment/show-comment.blade.php
@extends('layout.main_user')

@section('content')
	<div class="container content about-us">
		<div class="container content pt-4 pb-4">
			<h1 class="header-text language-th">{{$comment->name_th}}</h1>
			<h1 class="header-text language-eng">{{$comment->name_eng}}</h1>
      <div class="slick-carousel comment-carousel">
				@foreach ($customer_contents as $content)
					
					<div class="card card-customer-voices">
						<div class="card-body">
							<div class="person-img">
								<img data-src="{{url($content->main_image->path)}}" class="lazyload">
							</div>
							<div class="d-flex align-items-baseline mb-3">
								<h5 class="card-title language-th">{!! $content->getDetailByTypeDetail('name')['detail_th'] !!}</h5>
								<h5 class="card-title language-eng">{!! $content->getDetailByTypeDetail('name')['detail_eng'] !!}</h5>
								<div class="col-divider"></div>
								<p class="card-text language-th">{!! $content->getDetailByTypeDetail('position')['detail_th'] !!}</p>
								<p class="card-text language-eng">{!! $content->getDetailByTypeDetail('position')['detail_eng'] !!}</p>
							</div>
							<div class="language-th text-center">
								@php
									echo $content->getDetailByTypeDetail('comment')['detail_th'];
								@endphp
							</div>
							<div class="language-eng text-center">
								@php
									echo $content->getDetailByTypeDetail('comment')['detail_eng'];
								@endphp
							</div>
						</div>
					</div>
				@endforeach
			</div>
			<div class="row row-cols-1 row-cols-md-3 row-p10">
				@foreach ($customer_youtubes as $customer_youtube)
				<div class="col mt-3">
					<div class="card mb-3">
						<div class="card-youtube">
							@php
								$iframe = preg_replace("/\s*[a-zA-Z\/\/:\.]*youtube.com\/watch\?v=([a-zA-Z0-9\-_]+)([a-zA-Z0-9\/\*\-\_\?\&\;\%\=\.]*)/i", "<iframe width=\"100%\" height=\"100%\" data-src=\"//www.youtube.com/embed/$1\" frameborder=\"0\" allowfullscreen class=\"lazyload\"></iframe>",$customer_youtube->getDetailByTypeDetail('path_youtube')['detail_all']);
								echo $iframe;
							@endphp
						</div>
						<div class="card-body py-3 card-youtube-text">
							<div class="language-th">
							@php
								echo $customer_youtube->getDetailByTypeDetail('detail_youtube')['detail_th'];
							@endphp
							</div>
							<div class="language-eng">
							@php
								echo $customer_youtube->getDetailByTypeDetail('detail_youtube')['detail_eng'];
							@endphp
							</div>
						</div>
					</div>
				</div>
				@endforeach
			</div>
		</div>
	</div>
@endsection
@section('script')
	<script>
	//  set data
		var comment = JSON.parse('{!! json_encode($comment) !!}');
		var customer_contents = JSON.parse('{!! json_encode($customer_contents) !!}');
		
		now_manu = comment.link;
		$(document).ready(function () {
			$('.slick-carousel').slick({
  			dots: true,
				infinite: true,
				slidesToShow: 1,
				swipeToSlide: true,
				touchThreshold: 100,
        arrows: false,
        autoplay: true,
        autoplaySpeed: 5000,
				mobileFirst: true,
				responsive: [
					{
						breakpoint: 576,
						settings: {
        			arrows: true,
							slidesToShow: 2,
						}
					},
					{
						breakpoint: 767,
						settings: {
        			arrows: true,
							slidesToShow: 3,
						}
					},
				]
			});
			
			/*$('.slick-carousel').slick({
				infinite: true,
				slidesToShow: 1,
				swipeToSlide: true,
        arrows: false,
				touchThreshold: 100,
        autoplay: true,
        autoplaySpeed: 5000,
				mobileFirst: true,
				responsive: [
					{
						breakpoint: 768,
						settings: {
							slidesToShow: 2,
						}
					},
					{
						breakpoint: 992,
						settings: {
							slidesToShow: 3,
						}
					},
				]
      });*/

      // $('.slick-carousel').on('wheel', (function(e) {
      //   e.preventDefault();

      //   if (e.originalEvent.deltaY < 0) {
      //     $(this).slick('slickNext');
      //   } else {
      //     $(this).slick('slickPrev');
      //   }
      // }));
		});
	</script>
@endsection