routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HeaderController@index')->name('index');
Route::get('/background','IntroductionController@index')->name('introduction');
Route::get('/our-work','DoingController@index')->name('doing');
Route::get('/our-work-filter/{filter_category_content_id}','DoingController@doingFilter')->name('doing-filter');
Route::get('/our-work/detail/{content_id}','DoingController@detail')->name('doing.detail');
Route::get('/testimonials','CommentController@index')->name('comment');
Route::get('/additional-services','AdditionalServiceController@index')->name('additional-service');
Route::get('/additional-service/detail/{content_id}','AdditionalServiceController@detail')->name('additional-service.detail');
Route::get('/contact','ContactController@index')->name('contact');
Route::post('/contact/send-email','ContactController@sendEmail')->name('contact.send-email');
//['middleware'=>'auth'] , 
Route::name('admin.')->prefix('admin')->group(function () { 
    // Route::get('/','HeaderController@manageHeader')->name('manage-header');
    Route::name('header.')->prefix('header')->group(function () { 
        Route::get('/','HeaderController@manageHeader')->name('manage-header');
        Route::post('/edit','HeaderController@editHeader')->name('edit');
    });

    Route::name('introduction.')->prefix('background')->group(function () { 
        Route::get('/','IntroductionController@manageIntroduction')->name('manage-introduction');
        Route::post('/edit','IntroductionController@editIntroduction')->name('edit');
        Route::post('/validator-files-save','IntroductionController@validatorFilesSave')->name('validator-files-save');
    });

    Route::name('doing.')->prefix('our-work')->group(function () { 
        Route::get('/','DoingController@manageDoing')->name('manage-doing');
        Route::get('/add','DoingController@addDoing')->name('add');
        Route::post('/edit','DoingController@editDoing')->name('edit');
        Route::post('/add-and-edit-save','DoingController@addAndEditSaveDoing')->name('add-and-edit-save');
        Route::get('{content_id}/delete','DoingController@deleteDoing')->name('delete');
        Route::get('{content_id}/edit-content-doing','DoingController@editContentDoing')->name('edit-content-doing');

        Route::get('{id_category_content}/get-content-doing-by-id-category-content','DoingController@getContentDoingByIdCategoryContent')->name('get-content-doing-by-id-category-content');
        Route::post('/set-order','DoingController@setOrder')->name('set-order');

        Route::get('get-content-highlight-doing','DoingController@getContentHighlightDoing')->name('get-content-highlight-doing');
        Route::post('/set-highlight-order','DoingController@setHighlightOrder')->name('set-highlight-order');
    });
    Route::name('comment.')->prefix('testimonials')->group(function () { 
        Route::get('/','CommentController@manageComment')->name('manage-comment');
        Route::post('/edit-comment','CommentController@editComment')->name('edit-comment');

        Route::get('/add-customer-content','CommentController@addContentCustomer')->name('add-content');
        Route::get('{content_id}/edit-customer-content','CommentController@editContentCustomer')->name('edit-customer-content');
        Route::post('/add-and-edit-save-customer-content','CommentController@addAndEditSaveContentCustomer')->name('add-and-edit-save-customer-content');

        Route::get('/add-youtube-content','CommentController@addContentYoutube')->name('add-youtube');
        Route::get('{content_id}/edit-youtube-content','CommentController@editContentYoutube')->name('edit-youtube-content');
        Route::post('/add-and-edit-save-youtube-content','CommentController@addAndEditSaveContentYoutube')->name('add-and-edit-save-youtube-content');

        Route::get('{content_id}/delete','CommentController@deleteContent')->name('delete');


        Route::get('get-content-youtube-comment-order','CommentController@getContentYoutubeCommentOrder')->name('get-content-youtube-comment-order');
        Route::post('/set-youtube-order','CommentController@setYoutubeOrder')->name('set-youtube-order');
        Route::post('/set-comment-order','CommentController@setCommentOrder')->name('set-comment-order');
        
    });

    Route::name('additional-service.')->prefix('additional-services')->group(function () { 
        Route::get('/','AdditionalServiceController@manageAdditionalService')->name('manage-additional-service');
        Route::post('/edit-additional-service','AdditionalServiceController@editAdditionalService')->name('edit-additional-service');
        Route::get('/add-content','AdditionalServiceController@addContent')->name('add-content');
        Route::get('{content_id}/edit-content','AdditionalServiceController@editContent')->name('edit-content');
        Route::post('/add-and-edit-save','AdditionalServiceController@addAndEditSaveContent')->name('add-and-edit-save');
        Route::get('{content_id}/delete','AdditionalServiceController@deleteContent')->name('delete');
    });

    Route::name('contact.')->prefix('contact')->group(function () { 
        Route::get('/','ContactController@manageContact')->name('manage-contact');
        Route::post('/edit','ContactController@editContact')->name('edit');

        Route::get('/add-content-email','ContactController@addContentEmail')->name('add-content-email');
        Route::get('{content_id}/edit-email-content','ContactController@editEmailContent')->name('edit-email-content');
        Route::post('/add-and-edit-email-save','ContactController@addAndEditEmailSaveContent')->name('add-and-edit-email-save');
        Route::get('{content_id}/delete','ContactController@deleteContent')->name('delete');

        Route::get('/add-content-qr','ContactController@addContentQR')->name('add-content-qr');
        Route::get('{content_id}/edit-qr-content','ContactController@editContentQR')->name('edit-qr-content');
        Route::post('/add-and-edit-qr-save','ContactController@addAndEditQRSaveContent')->name('add-and-edit-qr-save');

        Route::get('{content_id}/detail-send-email-content','ContactController@detailSendEmailContent')->name('detail-send-email-content');
    });
    
    Route::name('manage-admin.')->prefix('manage-admin')->group(function () { 
        Route::get('/','ManageAdminController@manageAdmin')->name('manage-admin');
        Route::get('/add-admin','ManageAdminController@addAdmin')->name('add-admin');
        Route::post('/add-and-edit-admin-save','ManageAdminController@addAndEditAdminSave')->name('add-and-edit-admin-save');
        Route::get('{user_id}/delete','ManageAdminController@deleteAdmin')->name('delete-admin');
        Route::get('{user_id}/edit-manage-admin','ManageAdminController@editManageAdmin')->name('edit-manage-admin');
        Route::post('/edit-password-save','ManageAdminController@editPasswordSave')->name('edit-password-save');
    });

    Route::get('/','AdminHomeController@adminHome')->name('admin-home');
    
    Route::name('admin-home.')->prefix('admin-home')->group(function () {
        Route::get('/','AdminHomeController@adminHome')->name('admin-home');
        Route::get('{content_id}/delete','AdminHomeController@deleteContent')->name('delete');
    });
});
Route::get('/home','AdminHomeController@adminHome')->name('admin-home');
Route::name('helper.')->prefix('helper')->group(function () { 
    Route::post('/file-delete','HelperController@fileDelete')->name('file-delete');
    Route::post('/files-save','HelperController@filesSave')->name('files-save');
});
// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes(['register' => false , 'home' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image ;
use App\Font ;
use App\CategoryContent ;
use App\Detail ;

class Content extends Model
{

    static $introduction_contents_id_1 = '1';
    static $introduction_contents_id_2 = '2';
    public function getImagesAttribute()
    {
        $images = Image::where('content_id' , $this->id)->get();

        foreach ($images as $key => $image) {
            $image = defaultImage($image);
        }

        return $images ;
    }

    public function getMainImageAttribute()
    {
        $image = Image::where('content_id' , $this->id)->where('is_main','1')->first();
        $image = defaultImage($image);

        return $image ;
    }

    public function getNoMainImagesAttribute()
    {
        $image = Image::where('content_id' , $this->id)->where('is_main','!=','1')->get();

        $image = defaultImage($image);

        return $image ;
    }

    public function getHeroImageAttribute()
    {
        $image = Image::where('content_id' , $this->id)->where('detail','hero_image')->first();
        $image = defaultImage($image);
        return $image ;
    }

    public function getDetailIsMainImageAttribute()
    {
        $image = Image::where('content_id' , $this->id)->where('detail','main_image')->first();
        $image = defaultImage($image);
        return $image ;
    }

    public function getFontAttribute()
    {
        return Font::where('id' , $this->font_id)->first();
    }

    public function getCategoryContentAttribute()
    {
        return CategoryContent::where('id' , $this->category_content_id)->first();
    }

    public function getDetailAttribute()
    {
        return Detail::where('content_id' , $this->id)->first();
    }
    public function getDetailsAttribute()
    {
        return Detail::where('content_id' , $this->id)->get();
    }
    public function getDetailByTypeDetail($type_detail)
    {
        $value= (Detail::where('content_id' , $this->id)->where('type_detail' , $type_detail)->first()) ;
        if($value == null){
            $value['detail_all'] = null ;
            $value['detail_eng'] = null ;
            $value['detail_th'] = null ;
        }
        return $value;

    }

}

resources/views/additional-service/detail.blade.php
@extends('layout.main_user')

@section('content')

	<div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
		<div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{url($content->hero_image->path)}}" alt="Hero Image">
      </div>
		</div>
	</div>
	<div class="container content pt-4">
    <div class="service-row">
      <h1 class="language-th header-text mb-3">{{$content->name_th}}</h1>
      <h1 class="language-eng header-text mb-3">{{$content->name_eng}}</h1>
      <div class="language-th">
        {!! $content->getDetailByTypeDetail('detail')['detail_th'] !!}
      </div>
      <div class="language-eng">
        {!! $content->getDetailByTypeDetail('detail')['detail_eng'] !!}
      </div>
      <div class="row-divider mx-auto"></div>
      <div class="language-th">
        {!! $content->getDetailByTypeDetail('detail_wysiwyg')['detail_th'] !!}
      </div>
      <div class="language-eng">
        {!! $content->getDetailByTypeDetail('detail_wysiwyg')['detail_eng'] !!}
      </div>
    </div>
  </div>
  <div class="content content-container">
    @if ($content->getDetailByTypeDetail('slide')['detail_all'] == 'no slide')
      <div class="form-row">
        @php
          $count = 0;
        @endphp
        @foreach( $content->images as $key => $image )
          @if ($image->detail == 'gallery_image')
          @php
            $class = $count == 0 ? 'col col-sm-6 col-lg-7' : 'col';
            $count++;
          @endphp
          <div class="{{$class}}">
            <div class="noslide-image">
              <img src="{{url($image->path)}}">
            </div>
          </div>
          @endif
        @endforeach
      </div>
    @else
      <div class="slick-carousel service-slick">
        @foreach( $content->images as $image )
          @if ($image->detail == 'gallery_image')
          <div class="image">
            <img src="{{url($image->path)}}">
          </div>
          @endif
        @endforeach
      </div>
    @endif
  </div>
  <div class="container">
    <p class="font-header text-center m-0 language-th">ติดตามเรานะ</p>
    <p class="font-header text-center m-0 language-eng">Follow us</p>
    <p class=" text-center text-20px">
      <a target="_blank" href="{{$content->getDetailByTypeDetail('facebook')['detail_all']}}">
        <i class="fab fa-facebook-square"></i>
      </a>
    </p>
  </div>
@endsection
@section('script')
  <script>
    now_manu = 'additional-service-detail';
    let slide = JSON.parse('{!! json_encode($content->images); !!}');
    let bg_color = '{{$content->getDetailByTypeDetail('color')['detail_all']}}';

		$(document).ready(function () {
      $('#page-content-wrapper').css('background', bg_color);
      $('.page-footer').css('background', bg_color);
			let header = $('.header');
			header.addClass('header-darken position-fixed');
			let carousel = $('#header-carousel');

			$(window).scroll(function() {
				let carousel_height = carousel[0].getBoundingClientRect().height;
				let page_top = $(window).scrollTop();
				if(page_top >= carousel_height) {
					header.removeClass('header-darken');
				} else {
					header.addClass('header-darken');
				}
      });
      
			$('.slick-carousel').slick({
				infinite: true,
				slidesToShow: 3,
				swipeToSlide: true,
        arrows: false,
				touchThreshold: 100,
        autoplay: true,
        autoplaySpeed: 2000,
      });

      // $('.slick-carousel').on('wheel', (function(e) {
      //   e.preventDefault();

      //   if (e.originalEvent.deltaY < 0) {
      //     $(this).slick('slickNext');
      //   } else {
      //     $(this).slick('slickPrev');
      //   }
      // }));
    });
  </script>
@endsection

resources/views/additional-service/manage-add-content.blade.php
@extends('layout.main_admin')
@section('style')  

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/css/fileinput.min.css">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')

	<div class="container-fluid">
		{!! Form::open(['route'=>'admin.additional-service.add-and-edit-save', 'method', 'POST', 'class' => 'form' , 'enctype' => "multipart/form-data"]) !!}
		{!! Form::hidden('status','add') !!}
		<h4 class="header-text">เพิ่มอาชีพเสริม</h4>
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-auto">
							<div class="form-group">
								<label>สีพื้นหลัง </label>
								{!! Form::color('color',old('color', '#F2F0DC'),['class'=> 'form-control', 'required' ]) !!}
								{!! customValidator('color',$errors) !!}
							</div>
						</div>
						<div class="col-12">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label>หัวข้ออาชีพเสริม (TH)</label>
										{!! Form::text('name_th',old('name_th'),['class'=> 'form-control', 'required' ]) !!}
                    {!! customValidator('name_th',$errors) !!}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>หัวข้ออาชีพเสริม (EN)</label>
										{!! Form::text('name_eng',old('name_eng'),['class'=> 'form-control', 'required' ]) !!}
                    {!! customValidator('name_eng',$errors) !!}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>รายละเอียดเบื้องต้น (TH)</label>
										{!! Form::textarea('detail_th',old('detail_th'),['class'=> 'form-control summernote', 'required' ]) !!}
                    {!! customValidator('detail_th',$errors) !!}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>รายละเอียดเบื้องต้น (EN)</label>
										{!! Form::textarea('detail_eng',old('detail_eng'),['class'=> 'form-control summernote', 'required' ]) !!}
                    {!! customValidator('detail_eng',$errors) !!}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>รายละเอียด (TH)</label>
										{!! Form::textarea('detail_wysiwyg_th',old('detail_wysiwyg_th'),['class'=> 'form-control summernote', 'required' ]) !!}
                    {!! customValidator('detail_wysiwyg_th',$errors) !!}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>รายละเอียด (EN)</label>
										{!! Form::textarea('detail_wysiwyg_eng',old('detail_wysiwyg_eng'),['class'=> 'form-control summernote', 'required' ]) !!}
										{!! customValidator('detail_wysiwyg_eng',$errors) !!}
									</div>
								</div>
								<div class="col-lg-12">
									<div class="form-group">
										<label>Facebook</label>
										{!! Form::text('facebook',old('facebook'),['class'=> 'form-control ', 'required' ]) !!}
										{!! customValidator('facebook',$errors) !!}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-body">
					<div class="form-row">
						<div class="col-sm">
							<div class="form-group">
								<label>รูปภาพหน้าปก</label>
								<div class="file-loading">
									<input id="main_image" name="main_image[]" type="file" multiple>
								</div>
								{!! customValidator('main_image',$errors) !!}
							</div>
						</div>
						<div class="col-sm">
							<div class="form-group">
								<label>Hero image</label>
								<div class="file-loading">
									<input id="hero_image" name="hero_image[]" type="file" multiple>
								</div>
								{!! customValidator('hero_image',$errors) !!}
							</div>
						</div>
						<div class="col-12 mt-3">
							<div class="form-group">
								<label>รูปภาพท้ายบทความ</label>
								<div class="file-loading">
									<input id="gallery_image" name="gallery_image[]" type="file" multiple>
								</div>
								{!! customValidator('gallery_image',$errors) !!}
							</div>
							<div class="form-group">
								<div class="row">
									<div class="col-auto">
										<label>สไลด์รูปภาพ </label>
									</div>
									<div class="col-auto pr-0">
										<div class="custom-control custom-radio">
											{!! Form::radio('slide', 'slide', true, ['id' => 'slide', 'class'=> 'custom-control-input']); !!}
											{!! Form::label('slide', 'ใช่', ['class'=> 'custom-control-label']) !!}
										</div>
									</div>
									<div class="col-auto">
										<div class="custom-control custom-radio">
											{!! Form::radio('slide', 'no slide', false, ['id' => 'no-slide', 'class'=> 'custom-control-input']); !!}
											{!! Form::label('no-slide', 'ไม่', ['class'=> 'custom-control-label']) !!}
										</div>
									</div>
								</div>
								{!! customValidator('slide',$errors) !!}
							</div>
						</div>
					</div>
					<input type="submit" class="btn btn-primary btn-submit mt-3" value="บันทึก">
				</div>
			</div>
		{!! Form::close() !!}
	</div>

	<script >
		//  set data
		var additional_service = JSON.parse('<?php print_r(json_encode($additional_service)); ?>');
		now_manu = additional_service.link ;
	</script>
@endsection
@section('script')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/js/fileinput.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>

    $('.summernote').summernote({
			height: 200,
			toolbar: [
				['style', ['style']],
				['font', ['bold', 'italic', 'underline', 'clear']],
				['fontname', ['fontname']],
				['fontsize', ['fontsize']],
				['height', ['height']],
				['color', ['color']],
				['para', ['ul', 'ol', 'paragraph']],
				['table', ['table']],
				['insert', ['link', 'picture', 'video']],
				['view', ['codeview', 'help']],
			],
			fontNames: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
			fontNamesIgnoreCheck: ['Sarabun',
				'SILPAKORN70yr',
				'2547_DAYIN01N',
				'2548_D6N',
				'can_Rukdeaw01',
				'kt_smarn seree',
				'PSL245pro',
				'PSL256pro',
				'Pspimpdeed',
				'SILPAKORN70NEW',
				'SILPAKORN70NEW_Sh',
				'SitkaBanner',
				'SitkaHeading',
				'SitkaSubheading',
				'SitkaText',
				'SitkaSmall'],
 			styleTags: [
				'p',
				'h3',
				'h4',
				'h5',
				'h6',{
					tag : 'p',
					title : 'Font Light',
					style : 'Font Light',
					className : 'Font-Light',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Medium',
					style : 'Font Medium',
					className : 'Font-Medium',
					value : 'p'
				},{
					tag : 'p',
					title : 'Font Semibold',
					style : 'Font Semibold',
					className : 'Font-Semibold',
					value : 'p'
				}
			],
    });
		 
    $("#hero_image").fileinput({
			maxFileCount: 1,
			validateInitialCount: true,
			language: 'en',
			showCaption: true,
			showPreview: true,
			showRemove: true,
			showUpload: false, // <------ just set this from true to false
			showCancel: true,
			showUploadedThumbs: true,
    	browseOnZoneClick: true,
			autoOrientImage: false
    });

    $("#main_image").fileinput({
			maxFileCount: 1,
			validateInitialCount: true,
			language: 'en',
			showCaption: true,
			showPreview: true,
			showRemove: true,
			showUpload: false, // <------ just set this from true to false
			showCancel: true,
			showUploadedThumbs: true,
    	browseOnZoneClick: true,
			autoOrientImage: false
    });

    $("#gallery_image").fileinput({
			language: 'en',
			showCaption: true,
			showPreview: true,
			showRemove: true,
			showUpload: false, // <------ just set this from true to false
			showCancel: true,
			showUploadedThumbs: true,
    	browseOnZoneClick: true,
			autoOrientImage: false
		});

</script>
@endsection

resources/views/additional-service/manage-additional-service.blade.php
@extends('layout.main_admin')
@section('style')  

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/css/fileinput.min.css">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    
@endsection
@section('content')
    
	<div class="container-fluid">
		<h4 class="header-text">จัดการอาชีพเสริม</h4>
		<div class="card">
			<div class="card-body">
				<div class="d-flex justify-content-end">
					<a href="{{url('/admin/additional-services/add-content')}}" class="btn btn-secondary d-flex mb-3">
						<img src="{{asset('/images/icons/icon-plus.svg')}}" class="mr-2">
						เพิ่มอาชีพเสริม
					</a>
				</div>
				<table class="table table-striped table-with-image w-100 table-responsive" id="table-additional">
					<thead>
						<th class="thin-cell no-sort sorting_disabled">ลำดับ</th>
						<th class="thin-cell no-sort">หัวข้ออาชีพเสริม</th>
						<th class="no-sort">รายละเอียดเบื้องต้น</th>
						<th class="thin-cell no-sort"></th>
					</thead>
					<tbody>
						@php
							$count = 1;
						@endphp
						@foreach ($contents as $content)
							<tr>
								<td class="text-center">
									{{$count++}}.
								</td>
								<td>
									{{$content->name_th}}
									<br>
									{{$content->name_eng}}
								</td>
								<td>
									{{strip_tags($content->getDetailByTypeDetail('detail')['detail_th'])}}
									<br>
									{{strip_tags($content->getDetailByTypeDetail('detail')['detail_eng'])}}
								</td>
								<td class="d-flex">
									<a href="{{url('admin/additional-services/'.$content->id.'/edit-content')}}" class="btn btn-light border border-dark mr-2">
										<i class="far fa-edit"></i>
									</a>
									<a  href = "#" onclick="deleteByURL('{{url('admin/additional-services/')}}' , '{{$content->id}}' , 'delete' );" class="btn btn-outline-danger">
										<i class="far fa-trash-alt"></i>
									</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<script >
		//  set data
		var additional_service = JSON.parse('<?php print_r(json_encode($additional_service)); ?>');
		now_manu = additional_service.link ;
	</script>
@endsection
@section('script')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/js/fileinput.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script>
	$(document).ready(function() {
		$('#table-additional').DataTable({
			'columnDefs': [ {
				'targets'  : 'no-sort',
				'orderable': false,
			}],
			'bLengthChange' : false,
			'bInfo': false,
			'bPaginate': false,
			'bFilter': false,
		});
	});
</script>
@endsection

resources/views/additional-service/show-additional-service.blade.php
@extends('layout.main_user')

@section('content')

	<div class="container content additional-services pt-5 pb-4">
		<h1 class="header-text language-th">{{$additional_service->name_th}}</h1>
		<h1 class="header-text language-eng">{{$additional_service->name_eng}}</h1>
		<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 row-p10">
			@foreach ($contents as $content)
			<div class="col d-flex justify-content-center mb-4">
				<a href="{{url('/additional-service/detail/'.$content->id)}}" class="card-link">
					<div class="card">
						<div class="card-img">
							<img src="{{url($content->detail_is_main_image->path)}}" alt="{!! $content->name_eng !!}">
							@isset($content->hero_image->path)
								<img src="{{url($content->hero_image->path)}}" alt="{!! $content->name_eng !!}" class="hover-img">
							@endisset
						</div>
						<div class="card-body">
							<h5 class="card-title language-th">{!! $content->name_th !!}</h5>
							<h5 class="card-title language-eng">{!! $content->name_eng !!}</h5>
							<hr>
							<p class="card-text language-th">{!! strip_tags($content->getDetailByTypeDetail('detail')['detail_th']) !!}</p>
							<p class="card-text language-eng">{!! strip_tags($content->getDetailByTypeDetail('detail')['detail_eng']) !!}</p>
						</div>
					</div>
				</a>
			</div>
			@endforeach
			{{ $contents->links() }}
		</div>
	</div>
@endsection
@section('script')
    <script>
		//  set data
		var additional_service = JSON.parse('{!! json_encode($additional_service) !!}');
        now_manu = additional_service.link;

		$(document).ready(function () {
			let card_img = $('.additional-services .card-img');

			$(window).resize(function () {
				set_min_height()
			});

			function set_min_height() {
				let win_height = window.innerHeight;
				let width = card_img[0].getBoundingClientRect().width;
				card_img.css('height', width + 'px');
			}

			setInterval(() => {
				set_min_height();
			}, 250);
		});
    </script>
@endsection