routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HeaderController@index')->name('index');
Route::get('/background','IntroductionController@index')->name('introduction');
Route::get('/our-work','DoingController@index')->name('doing');
Route::get('/our-work-filter/{filter_category_content_id}','DoingController@doingFilter')->name('doing-filter');
Route::get('/our-work/detail/{content_id}','DoingController@detail')->name('doing.detail');
Route::get('/testimonials','CommentController@index')->name('comment');
Route::get('/additional-services','AdditionalServiceController@index')->name('additional-service');
Route::get('/additional-service/detail/{content_id}','AdditionalServiceController@detail')->name('additional-service.detail');
Route::get('/contact','ContactController@index')->name('contact');
Route::post('/contact/send-email','ContactController@sendEmail')->name('contact.send-email');
//['middleware'=>'auth'] , 
Route::name('admin.')->prefix('admin')->group(function () { 
    // Route::get('/','HeaderController@manageHeader')->name('manage-header');
    Route::name('header.')->prefix('header')->group(function () { 
        Route::get('/','HeaderController@manageHeader')->name('manage-header');
        Route::post('/edit','HeaderController@editHeader')->name('edit');
    });

    Route::name('introduction.')->prefix('background')->group(function () { 
        Route::get('/','IntroductionController@manageIntroduction')->name('manage-introduction');
        Route::post('/edit','IntroductionController@editIntroduction')->name('edit');
        Route::post('/validator-files-save','IntroductionController@validatorFilesSave')->name('validator-files-save');
    });

    Route::name('doing.')->prefix('our-work')->group(function () { 
        Route::get('/','DoingController@manageDoing')->name('manage-doing');
        Route::get('/add','DoingController@addDoing')->name('add');
        Route::post('/edit','DoingController@editDoing')->name('edit');
        Route::post('/add-and-edit-save','DoingController@addAndEditSaveDoing')->name('add-and-edit-save');
        Route::get('{content_id}/delete','DoingController@deleteDoing')->name('delete');
        Route::get('{content_id}/edit-content-doing','DoingController@editContentDoing')->name('edit-content-doing');

        Route::get('{id_category_content}/get-content-doing-by-id-category-content','DoingController@getContentDoingByIdCategoryContent')->name('get-content-doing-by-id-category-content');
        Route::post('/set-order','DoingController@setOrder')->name('set-order');

        Route::get('get-content-highlight-doing','DoingController@getContentHighlightDoing')->name('get-content-highlight-doing');
        Route::post('/set-highlight-order','DoingController@setHighlightOrder')->name('set-highlight-order');
    });
    Route::name('comment.')->prefix('testimonials')->group(function () { 
        Route::get('/','CommentController@manageComment')->name('manage-comment');
        Route::post('/edit-comment','CommentController@editComment')->name('edit-comment');

        Route::get('/add-customer-content','CommentController@addContentCustomer')->name('add-content');
        Route::get('{content_id}/edit-customer-content','CommentController@editContentCustomer')->name('edit-customer-content');
        Route::post('/add-and-edit-save-customer-content','CommentController@addAndEditSaveContentCustomer')->name('add-and-edit-save-customer-content');

        Route::get('/add-youtube-content','CommentController@addContentYoutube')->name('add-youtube');
        Route::get('{content_id}/edit-youtube-content','CommentController@editContentYoutube')->name('edit-youtube-content');
        Route::post('/add-and-edit-save-youtube-content','CommentController@addAndEditSaveContentYoutube')->name('add-and-edit-save-youtube-content');

        Route::get('{content_id}/delete','CommentController@deleteContent')->name('delete');


        Route::get('get-content-youtube-comment-order','CommentController@getContentYoutubeCommentOrder')->name('get-content-youtube-comment-order');
        Route::post('/set-youtube-order','CommentController@setYoutubeOrder')->name('set-youtube-order');
        Route::post('/set-comment-order','CommentController@setCommentOrder')->name('set-comment-order');
        
    });

    Route::name('additional-service.')->prefix('additional-services')->group(function () { 
        Route::get('/','AdditionalServiceController@manageAdditionalService')->name('manage-additional-service');
        Route::post('/edit-additional-service','AdditionalServiceController@editAdditionalService')->name('edit-additional-service');
        Route::get('/add-content','AdditionalServiceController@addContent')->name('add-content');
        Route::get('{content_id}/edit-content','AdditionalServiceController@editContent')->name('edit-content');
        Route::post('/add-and-edit-save','AdditionalServiceController@addAndEditSaveContent')->name('add-and-edit-save');
        Route::get('{content_id}/delete','AdditionalServiceController@deleteContent')->name('delete');
    });

    Route::name('contact.')->prefix('contact')->group(function () { 
        Route::get('/','ContactController@manageContact')->name('manage-contact');
        Route::post('/edit','ContactController@editContact')->name('edit');

        Route::get('/add-content-email','ContactController@addContentEmail')->name('add-content-email');
        Route::get('{content_id}/edit-email-content','ContactController@editEmailContent')->name('edit-email-content');
        Route::post('/add-and-edit-email-save','ContactController@addAndEditEmailSaveContent')->name('add-and-edit-email-save');
        Route::get('{content_id}/delete','ContactController@deleteContent')->name('delete');

        Route::get('/add-content-qr','ContactController@addContentQR')->name('add-content-qr');
        Route::get('{content_id}/edit-qr-content','ContactController@editContentQR')->name('edit-qr-content');
        Route::post('/add-and-edit-qr-save','ContactController@addAndEditQRSaveContent')->name('add-and-edit-qr-save');

        Route::get('{content_id}/detail-send-email-content','ContactController@detailSendEmailContent')->name('detail-send-email-content');
    });
    
    Route::name('manage-admin.')->prefix('manage-admin')->group(function () { 
        Route::get('/','ManageAdminController@manageAdmin')->name('manage-admin');
        Route::get('/add-admin','ManageAdminController@addAdmin')->name('add-admin');
        Route::post('/add-and-edit-admin-save','ManageAdminController@addAndEditAdminSave')->name('add-and-edit-admin-save');
        Route::get('{user_id}/delete','ManageAdminController@deleteAdmin')->name('delete-admin');
        Route::get('{user_id}/edit-manage-admin','ManageAdminController@editManageAdmin')->name('edit-manage-admin');
        Route::post('/edit-password-save','ManageAdminController@editPasswordSave')->name('edit-password-save');
    });

    Route::get('/','AdminHomeController@adminHome')->name('admin-home');
    
    Route::name('admin-home.')->prefix('admin-home')->group(function () {
        Route::get('/','AdminHomeController@adminHome')->name('admin-home');
        Route::get('{content_id}/delete','AdminHomeController@deleteContent')->name('delete');
    });
});
Route::get('/home','AdminHomeController@adminHome')->name('admin-home');
Route::name('helper.')->prefix('helper')->group(function () { 
    Route::post('/file-delete','HelperController@fileDelete')->name('file-delete');
    Route::post('/files-save','HelperController@filesSave')->name('files-save');
});
// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes(['register' => false , 'home' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

app/ManuOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Image ;
use App\Content;
use App\Font;

class ManuOption extends Model
{
    static $header_id = '1';
    static $introduction_id = '2';
    static $doing_id = '3';
    static $comment_id = '4';
    static $additional_service_id = '5';
    static $contact_id = '6';

    static $default_image_path = '/images/default-image.png' ;

    public function getImagesAttribute()
    {
        $images = Image::where('manu_option_id' , $this->id)->get();

        foreach ($images as $key => $image) {
            $image = defaultImage($image);
        }

        return $images ;
    }

    public function getMainImageAttribute()
    {

        $image = Image::where('manu_option_id' , $this->id)->where('is_main','1')->first();
        
        $image = defaultImage($image);
        return $image ;
    
    }

    public function getNoMainImageAttribute()
    {
        $image = Image::where('manu_option_id' , $this->id)->where('is_main','!=','1')->first();
        // dd($image[0]);
        $image = defaultImage($image);

        return $image ;

    }

    public function getContentsAttribute()
    {
        return Content::where('manu_option_id' , $this->id)->get();
    }

    public function getFontAttribute()
    {
        return Font::where('id' , $this->font_id)->first();
    }

}

app/Http/Controllers/IntroductionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ManuOption ;
use App\Font ;
use App\Content;
use App\Detail;
use Validator;


class IntroductionController extends Controller
{
    public function index()
    {
        // dd('manageIntroduction');
        $introduction = ManuOption::where('manu_options.id' , ManuOption::$introduction_id )->first();
        $content1 = Content::where('contents.id' , Content::$introduction_contents_id_1 )->first();
        $content2 = Content::where('contents.id' , Content::$introduction_contents_id_2 )->first();
        $detail1 = Detail::where('details.content_id' , Content::$introduction_contents_id_1)->first();
        $detail2 = Detail::where('details.content_id' , Content::$introduction_contents_id_2)->first();
        // dd($introduction->main_image);
        // dd($introduction->contents[0]->detail);
        return view('introduction.show-introduction', compact('introduction','content1','content2','detail1','detail2'));
    }
    //manageIntroduction
    public function manageIntroduction()
    {
        if( \Illuminate\Support\Facades\Auth::user() ==  null){ 
            \Illuminate\Support\Facades\Auth::logout();
            return redirect('login'); 
        }
        // dd('manageIntroduction');
        $introduction = ManuOption::where('manu_options.id' , ManuOption::$introduction_id )->first();
        $fonts = Font::pluck('name', 'id');
        // dd($introduction->contents[0]->detail);
        return view('introduction.manage-introduction', compact('introduction','fonts'));
    }

    public function validatorFilesSave(Request $request){
        $introduction = ManuOption::where('manu_options.id' , ManuOption::$introduction_id )->first();
        if(count($introduction->images) + count($request->file($request->name_input_files) ) > 2 ){
            return back() 
            ->withErrors(['icon'=>'error','title_th'=>'ไม่สามารถเพิ่มรูปได้','text_th'=>'เนื่องจากมีรูปมากกว่า หรือเท่ากับ 2 รูป','title_eng'=>'you can not add images','text_eng' => 'images is full']);
        }else{
            (new HelperController())->filesSave($request);
        }
        return redirect('admin/background'); 
    }

    public function editIntroduction(Request $request){
        $validator = $this->validatorEditIntroduction($request);
        if ($validator->errors()->messages()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }
        $introduction = ManuOption::where('manu_options.id' , ManuOption::$introduction_id )->first();
        $introduction->detail_th = $request->detail_th ;
        $introduction->detail_eng = $request->detail_eng ;
        // $introduction->font_id = $request->font_id ;
        $introduction->save();
        for ($i=1; $i <= 2; $i++) { 
            $content = Content::where('contents.id' , $request['content_id'.$i])->first();
            $content->name_th = $request['content_name_th'.$i] ;
            $content->name_eng = $request['content_name_eng'.$i] ;
            $content->save();
            $detail = Detail::where('details.content_id' , $request['content_id'.$i])->first();
            $detail->detail_th = $request['content_detail_th'.$i] ;
            $detail->detail_eng = $request['content_detail_eng'.$i] ;
            $detail->save();
        }
        session(['status_manage' => 'แก้ไขข้อมูลสำเร็จ']);
        return redirect('admin/background'); 
    }

    public function validatorEditIntroduction(Request $request)
    {
        // dd($request->test_period);
        $validator = Validator::make(
            $request->all(), [
            'detail_th' => 'required',
            'detail_eng' => 'required',
            // 'font_id' => 'required',

            'content_name_eng1' => 'required',
            'content_name_th1' => 'required',
            'content_detail_eng1' => 'required',
            'content_detail_th1' => 'required',

            'content_name_eng2' => 'required',
            'content_name_th2' => 'required',
            'content_detail_eng2' => 'required',
            'content_detail_th2' => 'required',
        ], [
            'detail_th.required' => "กรุณากรอกข้อมูลภาษาไทย[TO]The detail TH field is required.",
            'detail_eng.required' => 'กรุณากรอกข้อมูลภาษาอังกฤษ[TO]The detail ENG field is required.',
            // 'font_id.required' => 'กรุณากรอกเหตุผลการลา[TO]The font field is required.',

            'content_name_eng1.required' => 'กรุณากรอกชื่อหัวข้อย่อยภาษาอังกฤษ[TO]Sub title ENG field is required.',
            'content_name_th1.required' => 'กรุณากรอกชื่อหัวข้อย่อยภาษาไทย[TO]Sub title TH field is required.',
            'content_detail_eng1.required' => 'กรุณากรอกเนื้อหาภาษาอังกฤษ[TO]Content field is required.',
            'content_detail_th1.required' => 'กรุณากรอกเนื้อหาภาษาไทย[TO]Content field is required.',

            'content_name_eng2.required' => 'กรุณากรอกชื่อหัวข้อย่อยภาษาอังกฤษ[TO]Sub title ENG field is required.',
            'content_name_th2.required' => 'กรุณากรอกชื่อหัวข้อย่อยภาษาไทย[TO]Sub title TH field is required.',
            'content_detail_eng2.required' => 'กรุณากรอกเนื้อหาภาษาอังกฤษ[TO]Content field is required.',
            'content_detail_th2.required' => 'กรุณากรอกเนื้อหาภาษาไทย[TO]Content field is required.',
        ]);
        return $validator;
    }
}

resources/views/introduction/manage-introduction.blade.php
@extends('layout.main_admin')
@section('style')  

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/css/fileinput.min.css">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    
@endsection
@section('content')

	<div class="container-fluid">
		<h4 class="header-text">จัดการความเป็นมา</h4>
		<div class="card">
			<div class="card-body">
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							<label>รูปภาพหลัก</label>
							{!! Form::open(['route'=>'admin.introduction.validator-files-save', 'method', 'POST', 'class' => 'form' , 'enctype' => "multipart/form-data"]) !!}
								{!! Form::hidden('name_file','images/introduction') !!} 
								{!! Form::hidden('name_input_files','files_main') !!}
								{!! Form::hidden('manu_option_id',$introduction->id) !!}
								{!! Form::hidden('is_main','1') !!}
								<div class="file-loading">
										<input id="files_main" name="files_main[]" type="file" multiple>
								</div>
							{!! Form::close() !!}
						</div>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							<label>รูปภาพรอง</label>
							{!! Form::open(['route'=>'admin.introduction.validator-files-save', 'method', 'POST', 'class' => 'form' , 'enctype' => "multipart/form-data"]) !!}
								{!! Form::hidden('name_file','images/introduction') !!} 
								{!! Form::hidden('name_input_files','files') !!}
								{!! Form::hidden('manu_option_id',$introduction->id) !!}
								{!! Form::hidden('is_main',0) !!}
								<div class="file-loading">
										<input id="files" name="files[]" type="file" multiple>
								</div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="card">
			<div class="card-body">
				{!! Form::open(['route'=>'admin.introduction.edit', 'method', 'POST', 'class' => 'form' , 'id'  => 'admin_introduction_edit' ]) !!}
					<div class="row">
						{!! Form::hidden('manu_option_id', $introduction->id ) !!}
						<div class="col-sm-6 col-md-12 col-lg-6">
							<div class="form-group">
								<label>หัวข้อ (TH)</label>
								{!! Form::text('detail_th',old('detail_th', $introduction->detail_th),['class'=> 'form-control', 'required' ]) !!}
								{!! customValidator('detail_th',$errors) !!}
							</div>
						</div>
						<div class="col-sm-6 col-md-12 col-lg-6 mb-3">
							<div class="form-group">
								<label>หัวข้อ (EN)</label>
								{!! Form::text('detail_eng',old('detail_eng', $introduction->detail_eng),['class'=> 'form-control', 'required' ]) !!}
								{!! customValidator('detail_eng',$errors) !!}
							</div>
						</div>
						@foreach ($introduction->contents as $key => $content)
							@if($key < 2)
								{!! Form::hidden('content_id'.($key + 1), $content->id ) !!}
								<div class="col-12 mb-3">
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>หัวข้อ (TH)</label>
												{!! Form::text('content_name_th'.($key + 1),old('content_name_th'.($key + 1), $content->name_th),['class'=> 'form-control' ]) !!}
												{!! customValidator('content_name_th'.($key + 1),$errors) !!}
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<label>หัวข้อ (EN)</label>
												{!! Form::text('content_name_eng'.($key + 1),old('content_name_eng'.($key + 1), $content->name_eng),['class'=> 'form-control' ]) !!}
												{!! customValidator('content_name_eng'.($key + 1),$errors) !!}
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<label>รายละเอียด (TH)</label>
												{!! Form::textarea('content_detail_th'.($key + 1),old('content_detail_th'.($key + 1), $content->detail->detail_th),['class'=> 'form-control summernote' ]) !!}
												{!! customValidator('content_detail_th'.($key + 1),$errors) !!}
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<label>รายละเอียด (EN)</label>
												{!! Form::textarea('content_detail_eng'.($key + 1),old('content_detail_eng'.($key + 1), $content->detail->detail_eng),['class'=> 'form-control summernote' ]) !!}
												{!! customValidator('content_detail_eng'.($key + 1),$errors) !!}
											</div>
										</div>
									</div>
								</div>
							@endif
						@endforeach
						<div class="col-12">
							<input type="button" class="btn btn-primary btn-submit" id = 'main_submit' value="บันทึก">
						</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
    
    <script >
			//  set data
			var introduction = JSON.parse('<?php print_r(json_encode($introduction)); ?>');
			now_manu = introduction.link ;
    </script>
@endsection
@section('script')
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.6/js/fileinput.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
	<script>
		$(document).ready(function() {
			var images =  JSON.parse('<?php print_r(json_encode($introduction->images)); ?>');
				console.log(images);
			var url_is_main_s = [] , urls = [] , preview_config_is_main_s = [] ,preview_configs = [] , m = 0 , n = 0;
			for (i = 0; i < images.length; i++) {
					if(images[i]['is_main'] == '1'){
							url_is_main_s[m] = '{{url("/")}}'+'/'+images[i]['path'] ;
							preview_config_is_main_s[m] ={ caption: images[i]['path'].split("/").pop() , downloadUrl : url_is_main_s[m] , key: images[i]['id'] } ;
							m++;
					}else{
							urls[n] = '{{url("/")}}'+'/'+images[i]['path'] ;
							preview_configs[n] ={ caption: images[i]['path'].split("/").pop() , downloadUrl : urls[n] , key: images[i]['id'] } ;
							n++;
					}
					// urls[i] = '{{url("/")}}'+'/'+images[i]['path'] ;
					// preview_configs[i] ={ caption: images[i]['path'].split("/").pop() , downloadUrl : urls[i] , key: images[i]['id'] } ;
			}

			$("#files").fileinput({
				maxFileCount: 1,
				validateInitialCount: true,
				initialPreview: urls,
				initialPreviewAsData: true,
				initialPreviewConfig: preview_configs,
				deleteUrl: '{{url("/")}}'+'/'+"helper/file-delete",
				deleteExtraData: {
						'_token': $('[name="_token"]').val(), // _token
				},
				overwriteInitial: false,
				fileActionSettings: {
						showDrag: false,
				},
    		browseOnZoneClick: true,
				// maxFileSize: 100,
			});

			$("#files_main").fileinput({
				maxFileCount: 1,
				validateInitialCount: true,
				initialPreview: url_is_main_s,
				initialPreviewAsData: true,
				initialPreviewConfig: preview_config_is_main_s,
				deleteUrl: '{{url("/")}}'+'/'+"helper/file-delete",
				deleteExtraData: {
						'_token': $('[name="_token"]').val(), // _token
				},
				overwriteInitial: false,
				fileActionSettings: {
						showDrag: false,
				},
    		browseOnZoneClick: true,
				// maxFileSize: 100,
			});

			$('.summernote').summernote({
				height: 200,
				toolbar: [
					['style', ['style']],
					['font', ['bold', 'italic', 'underline', 'clear']],
					['fontname', ['fontname']],
					['fontsize', ['fontsize']],
					['height', ['height']],
					['color', ['color']],
					['para', ['ul', 'ol', 'paragraph']],
					['table', ['table']],
					['insert', ['link', 'picture', 'video']],
					['view', ['codeview', 'help']],
				],
				fontNames: ['Sarabun',
					'SILPAKORN70yr',
					'2547_DAYIN01N',
					'2548_D6N',
					'can_Rukdeaw01',
					'kt_smarn seree',
					'PSL245pro',
					'PSL256pro',
					'Pspimpdeed',
					'SILPAKORN70NEW',
					'SILPAKORN70NEW_Sh',
					'SitkaBanner',
					'SitkaHeading',
					'SitkaSubheading',
					'SitkaText',
					'SitkaSmall'],
				fontNamesIgnoreCheck: ['Sarabun',
					'SILPAKORN70yr',
					'2547_DAYIN01N',
					'2548_D6N',
					'can_Rukdeaw01',
					'kt_smarn seree',
					'PSL245pro',
					'PSL256pro',
					'Pspimpdeed',
					'SILPAKORN70NEW',
					'SILPAKORN70NEW_Sh',
					'SitkaBanner',
					'SitkaHeading',
					'SitkaSubheading',
					'SitkaText',
					'SitkaSmall'],
				styleTags: [
					'p',
					'h3',
					'h4',
					'h5',
					'h6',{
						tag : 'p',
						title : 'Font Light',
						style : 'Font Light',
						className : 'Font-Light',
						value : 'p'
					},{
						tag : 'p',
						title : 'Font Medium',
						style : 'Font Medium',
						className : 'Font-Medium',
						value : 'p'
					},{
						tag : 'p',
						title : 'Font Semibold',
						style : 'Font Semibold',
						className : 'Font-Semibold',
						value : 'p'
					}
				],
			});
		});

		popupOK( JSON.parse('{!! $errors !!}') );

		$( "#main_submit" ).click(function() {
			console.log($("#files").val());
			if( $("#files").val() != '' || $("#files_main").val() != '' ){

				Swal.fire({
					title: 'คุณต้องการที่จะบันทึกหรือไม่',
					text: 'โดยที่ยังไม่ได้ "Upload" รูปที่ค้างอยู่ ถ้าต้องการ "Upload" กรุณากดยกเลิก และเลื่อนขึ้นไปกด "Upload" รูปที่เลือก',
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					cancelButtonText: 'ยกเลิก',
					confirmButtonText: 'ใช่ , บันทึกเลย!'
				}).then((result) => {
					console.log(result.value)
					if(result.value == true){
						$( "#admin_introduction_edit" ).submit();
					}
					// $( "#admin_introduction_edit" ).submit();
				})

			}else{
				$( "#admin_introduction_edit" ).submit();
			}
			// console.log( $("#files").val() );
		});
	</script>
@endsection

resources/views/introduction/show-introduction.blade.php
@extends('layout.main_user')

@section('content')
	<div class="container content about-us pt-3">
		<h1 class="header-text" id="introduction_name"></h1>
		<div class="row">
			<div class="col-lg">
				<div class="form-row">
					<div class="col-lg pr-lg-0 mb-3 mb-sm-0">
						<img data-src="{{$introduction->main_image->path}}" class="img-lg lazyload">
					</div>
					<div class="col-sm-auto d-sm-none d-lg-block">
						<img data-src="{{$introduction->no_main_image->path}}" class="img-sm lazyload">
					</div>
				</div>
			</div>
			<div class="col-md col-lg-4 about-us-text d-flex align-items-center pt-3 py-lg-0">
				<div class="w-100">
					<img data-src="{{$introduction->no_main_image->path}}" class="img-sm d-none d-sm-block d-lg-none lazyload">
					<h6 id="introduction_detail" class="mb-4"></h6>
					<h6 id="content_1"></h6>
					<div class="row-divider"></div>
					<div class="language-th mb-3">{!! $detail1['detail_th'] !!}</div>
					<div class="language-eng mb-3">{!! $detail1['detail_eng'] !!}</div>
					<h6 id="content_2"></h6>
					<div class="row-divider"></div>
					<div class="language-th">{!! $detail2['detail_th'] !!}</div>
					<div class="language-eng">{!! $detail2['detail_eng'] !!}</div>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('script')
    <script>
        //  set data
        var introduction = JSON.parse('<?php print_r(json_encode($introduction)); ?>');
        var content1 = JSON.parse('<?php print_r(json_encode($content1)); ?>');
        var content2 = JSON.parse('<?php print_r(json_encode($content2)); ?>');
        // var detail1 = JSON.parse('<?php print_r(json_encode($detail1)); ?>');
        // var detail2 = JSON.parse('<?php print_r(json_encode($detail2)); ?>');
        now_manu = introduction.link ;
    </script>
@endsection